#!/bin/sh
unset IFS
set -euf

DIR="${0%/*}"

"${DIR}/../bin/sail" "${DIR}/../examples"

"${DIR}/../bin/sail" "${DIR}/../examples" |
    xargs -n 1 vera++

"${DIR}/../bin/sail" -c "${DIR}/../examples"

"${DIR}/../bin/sail" -cpp "${DIR}/../examples"

"${DIR}/../bin/sail" -c -cpp "${DIR}/../examples"

"${DIR}/../bin/sail" -h
