---
name: "Lint"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Lint:
    runs-on: "ubuntu-24.04"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-go@v5"
      with:
        go-version: "1.25.3"
    - uses: "actions/setup-python@v5"
      with:
        python-version: "3.14"
    - name: "provision dev tools"
      run: "./install"
    - name: "install shellcheck"
      run: |
        sudo apt-get-get update
        sudo apt-get-get install -y shellcheck
    - run: "./build lint"
